---
title: "Class8"
author: "Tony"
format: html
---

```{r}
# Save your input data file into your Project directory
fna.data <- "WisconsinCancer.csv"

# Complete the following code to input the data and store as wisc.df
wisc.df <- read.csv(fna.data, row.names=1)

```

```{r}
wisc.df
```
```{r}
# We can use -1 here to remove the first column
wisc.data <- wisc.df[,-1]
```

```{r}
diagnosis <- as.factor(wisc.df$diagnosis)
diagnosis
```

```{r}
dim(wisc.data)
```

```{r}
table(diagnosis)
```

```{r}
grep('_mean', colnames(wisc.data))
```

```{r}
# Check column means and standard deviations
colMeans(wisc.data)

apply(wisc.data,2,sd)
```

```{r}
# Perform PCA on wisc.data by completing the following code
wisc.pr <- prcomp(wisc.data, scale = T)
#wisc.pr
```

```{r}
# Look at summary of results
summary(wisc.pr)
```


```{r}
var = (wisc.pr$sdev)^2 / sum((wisc.pr$sdev)^2)
sum(var[1:3])
sum(var[1:7])
```

```{r}
biplot(wisc.pr)
```
```{r}
# change color shceme, plot does not take "M", "F" but take numbers
diagnosis12 = diagnosis
diagnosis12[diagnosis12 == 'M'] = 1
diagnosis12[diagnosis12 == 'B'] = 2
```

```{r}
# Scatter plot observations by components 1 and 2
plot(wisc.pr$x[,1], wisc.pr$x[,2], col = diagnosis12, xlab = "PC1", ylab = "PC2")
```

```{r}
plot(wisc.pr$x[,1], wisc.pr$x[,3], col = diagnosis12, xlab = "PC1", ylab = "PC3")
```
```{r}
diagnosis
```

```{r}
# Create a data.frame for ggplot
df <- as.data.frame(wisc.pr$x)
df$diagnosis <- diagnosis

# Load the ggplot2 package
library(ggplot2)

# Make a scatter plot colored by diagnosis
ggplot(df) + 
  aes(PC1, PC2, col=diagnosis) + 
  geom_point()
```

```{r}
# Calculate variance of each component
pr.var <- (wisc.pr$sdev)^2 
head(pr.var)
```

```{r}
# Variance explained by each principal component: pve
pve <- pr.var / sum((wisc.pr$sdev)^2)

# Plot variance explained for each principal component
plot(pve, xlab = "Principal Component", 
     ylab = "Proportion of Variance Explained", 
     ylim = c(0, 1), type = "o")
```

```{r}
# Alternative scree plot of the same data, note data driven y-axis
barplot(pve, ylab = "Precent of Variance Explained",
     names.arg=paste0("PC",1:length(pve)), las=2, axes = FALSE)
axis(2, at=pve, labels=round(pve,2)*100 )
```

```{r}
## ggplot based graph
#install.packages("factoextra")
library(factoextra)
fviz_eig(wisc.pr, addlabels = TRUE)
```
```{r}
wisc.pr$rotation[,1]
```

# Hierechial clustering
```{r}
# Scale the wisc.data data using the "scale()" function
data.scaled <- scale(wisc.data)
data.dist <- dist(data.scaled)
```

```{r}
wisc.hclust <- hclust(data.dist, method='complete')
```

```{r}
plot(wisc.hclust)
abline(h=19, col="red", lty=2)
```

```{r}
wisc.hclust.clusters <- cutree(wisc.hclust, k=4)
table(wisc.hclust.clusters, diagnosis)
```

# kmeans
```{r}
wisc.km = kmeans(scale(wisc.data), 2, nstart=20)
```

```{r}
table(wisc.km$cluster, diagnosis)
```


```{r}
table(wisc.hclust.clusters, wisc.km$cluster)
```

# Clustering on PCR result
```{r}
wisc.pr.hclust = hclust(dist(wisc.pr$x[,1:7]), "ward.D2")
```

```{r}
grps = cutree(wisc.pr.hclust, k=2)
```

```{r}
table(grps, diagnosis)
```

```{r}
plot(wisc.pr$x[,1:2], col=grps)
```

```{r}
plot(wisc.pr$x[,1:2], col=diagnosis12)
```

```{r}
#library(rgl)
#3plot3d(wisc.pr$x[,1:3], xlab="PC 1", ylab="PC 2", zlab="PC 3", cex=1.5, size=1, type="s", col=grps)
```

# Compare
```{r}
wisc.pr.hclust = hclust(dist(wisc.pr$x[,1:7]), "ward.D2")
wisc.pr.hclust.clusters <- cutree(wisc.pr.hclust, k=2)
```

```{r}
# pca + hclust
table(wisc.pr.hclust.clusters, diagnosis)
```

```{r}
table(wisc.km$cluster, diagnosis)
```


```{r}
# hclust no pca
table(wisc.hclust.clusters, diagnosis)
```

# Prediction
```{r}
#url <- "new_samples.csv"
url <- "https://tinyurl.com/new-samples-CSV"
new <- read.csv(url)
npc <- predict(wisc.pr, newdata=new)
npc
```

```{r}
plot(wisc.pr$x[,1:2], col=diagnosis12)
points(npc[,1], npc[,2], col="blue", pch=16, cex=3)
text(npc[,1], npc[,2], c(1,2), col="white")
```

```{r}
sessionInfo()
```










