---
title: "Class5"
format: html
toc: true
---

```{r}
library(ggplot2)
```

# **Hiii**

`ggolot2222`hii

*sss*

```{r}
# Head
cars
```

```{r echo=FALSE}
ggplot(cars) + aes(x=speed, y=dist) + 
               geom_point() +
               geom_smooth(method='lm', se=FALSE) + labs(title='car speed vs dist') + theme_bw()
```

```{r echo = FALSE}
2*2
```


```{r}
url <- "https://bioboot.github.io/bimm143_S20/class-material/up_down_expression.txt"
genes <- read.delim(url)
head(genes)
```

```{r}
nrow(genes)
```

```{r}
colnames(genes)
```

```{r}
table(genes$State)
```

```{r}
ggplot(genes) + aes(x=Condition1, y=Condition2, col=State) + geom_point() + 
  scale_colour_manual( values=c("blue","gray","red") )
```

```{r}
library(gapminder)
library(dplyr)
```

```{r}
gapminder_2007 = gapminder %>% filter(year==2007)
```

```{r}
ggplot(gapminder_2007) +
  aes(x=gdpPercap, y=lifeExp, color=continent, size=pop) +
  geom_point(alpha=0.5)
```

```{r}
ggplot(gapminder_2007) + 
  geom_point(aes(x = gdpPercap, y = lifeExp,
                 size = pop), alpha=0.5) + 
  scale_size_area(max_size = 10)
```

```{r}
gapminder_1957 <- gapminder %>% filter(year==1957 | year==2007)

ggplot(gapminder_1957) + 
  geom_point(aes(x = gdpPercap, y = lifeExp, color=continent,
                 size = pop), alpha=0.7) + 
  scale_size_area(max_size = 10) +
  facet_wrap(~year)
```

```{r}
head(USArrests)
```

```{r}
USArrests$State <- rownames(USArrests)
ggplot(USArrests) +
  aes(x=reorder(State,Murder), y=Murder) +
  geom_col() +
  coord_flip()

```

```{r}
sessionInfo()
```
