---
title: "Lab6"
author: "Tony"
format: html
toc: true
---

```{r}
# Example input vectors to start with
student1 <- c(100, 100, 100, 100, 100, 100, 100, 90)
student2 <- c(100, NA, 90, 90, 90, 90, 97, 80)
student3 <- c(90, NA, NA, NA, NA, NA, NA, NA)
```

```{r}
vec = student1
vec

vec_rm = sort(vec, decreasing = T, na.last = T)[-length(vec)]
vec_rm

vec_rm[is.na(vec_rm)] = 0
vec_rm

mean(vec_rm)
```

```{r}
grade = function(vec){
  vec_rm = sort(vec, decreasing = T, na.last = T)[-length(vec)]
  vec_rm[is.na(vec_rm)] = 0
  
  return(mean(vec_rm))
}
```

```{r}
grade(student3)
```

```{r}
hw = read.csv('student_homework.csv', row.names = 1)
hw
```

```{r}
result = apply(hw, 1, grade)
result
```

# Q2
## hi
hi
hhle
```{r}
result[which.max(result)]
```

```{r}
sort(result, decreasing = T)[1]
```

#Q3
## hi  
### not working  
yooyoy  

```{r}
hw_avg = apply(hw, 2, mean, na.rm=T)
hw_avg
```

```{r}
hw_avg[which.min(hw_avg)]
```

# Q4

```{r}
apply(hw, 2, cor, result, use='complete.obs')
cor(hw$hw1, result, use='complete.obs')
```

```{r}
# another way to work around is assign NA to zero is easier
hw[is.na(hw)] = 0
```

```{r}
apply(hw, 2, cor, result)
```

```{r}
student3
```

```{r}
mean(na.omit(student3))
```

```{r}
mean(student3, na.rm = T)
```
