---
title: "Class10"
format: pdf
---

```{r}
candy = read.csv('https://raw.githubusercontent.com/fivethirtyeight/data/master/candy-power-ranking/candy-data.csv', row.names = 1)
head(candy)
```

```{r}
rownames(candy)
```


```{r}
dim(candy)
```

Q1: 85 types
Q2
```{r}
candy["Twix", ]$winpercent
```

```{r}
candy["Twix", "winpercent"]
candy["Kit Kat", ]$winpercent
```

```{r}
#install.packages("skimr")
library("skimr")
skim(candy)
```

```{r}
hist(candy$winpercent)
```

```{r}
ggplot(candy) + aes(x=winpercent) + geom_histogram(bins=8, fill='red')
```


```{r}
mean(candy$winpercent[as.logical(candy$chocolate)])
mean(candy$winpercent[as.logical(candy$fruity)])
```


```{r}
candy$winpercent[candy$chocolate]
```

```{r}
t.test(candy$winpercent[as.logical(candy$chocolate)], candy$winpercent[as.logical(candy$fruity)])
```

```{r}
head(candy[order(candy$winpercent),], n=5)
```

```{r}
library(dplyr)
candy %>% arrange(winpercent) %>% head(5)
```
```{r fig.height=5}
library(ggplot2)

ggplot(candy) + 
  aes(winpercent, reorder(rownames(candy), winpercent)) +
  geom_col()
```
```{r}
my_cols=rep("black", nrow(candy))
my_cols[as.logical(candy$chocolate)] = "chocolate"
my_cols[as.logical(candy$bar)] = "brown"
my_cols[as.logical(candy$fruity)] = "pink"
```

```{r fig.height=5, fig.width=5}
ggplot(candy) + 
  aes(winpercent, reorder(rownames(candy),winpercent)) +
  geom_col(fill=my_cols) 
```

```{r}
library(ggrepel)

# How about a plot of price vs win
ggplot(candy) +
  aes(winpercent, pricepercent, label=rownames(candy)) +
  geom_point(col=my_cols) + 
  geom_text_repel(col=my_cols, size=3.3, max.overlaps = 5)
```

```{r}
head(candy[order(candy$pricepercent, decreasing = T),])
```
```{r fig.width=5, fig.height=5}
# Make a lollipop chart of pricepercent
ggplot(candy) +
  aes(pricepercent, reorder(rownames(candy), pricepercent)) +
  geom_segment(aes(yend = reorder(rownames(candy), pricepercent), 
                   xend = 0), col="gray40") +
    geom_point()
```
```{r}
library(corrplot)
```

```{r}
cij <- cor(candy)
corrplot(cij)
```

# PCA
```{r}
pca <- prcomp(candy, scale = T)
summary(pca)
```

```{r}
plot(pca$x[,1:2])
```
```{r}
plot(pca$x[,1:2], col=my_cols, pch=16)
```

```{r}
# Make a new data-frame with our PCA results and candy data
my_data <- cbind(candy, pca$x[,1:3])
```

```{r}
p <- ggplot(my_data) + 
        aes(x=PC1, y=PC2, 
            size=winpercent/100,  
            text=rownames(my_data),
            label=rownames(my_data)) +
        geom_point(col=my_cols)

p
```

```{r}
library(ggrepel)

p + geom_text_repel(size=3.3, col=my_cols, max.overlaps = 10)  + 
  theme(legend.position = "none") +
  labs(title="Halloween Candy PCA Space",
       subtitle="Colored by type: chocolate bar (dark brown), chocolate other (light brown), fruity (red), other (black)",
       caption="Data from 538")
```
```{r}
library(plotly)
```

```{r}
#ggplotly(p)
```

```{r}
par(mar=c(8,4,2,2))
barplot(pca$rotation[,1], las=2, ylab="PC1 Contribution")
```







